import type { Content } from './schema.ts';

/**
 * Development seed. Used when Sanity isn't configured, so the app runs out of the box.
 * The real question bank lives in Sanity; import the full pilot bank with `npm run import:bank`.
 */
export const seedContent: Content = {
  industries: [
    {
      id: 'technology',
      name: 'Technology',
      color: '#6B3BFF',
      blurb: 'Engineering roles, from fundamentals to framework deep-dives.',
    },
    {
      id: 'm-and-a',
      name: 'Mergers & Acquisitions',
      color: '#00A676',
      blurb: 'People in deals: HR due diligence, separation and integration.',
    },
  ],
  roleFamilies: [
    { id: 'software-engineering', industryId: 'technology', name: 'Software Engineering' },
    { id: 'm-and-a', industryId: 'm-and-a', name: 'People in Deals' },
  ],
  specialisations: [
    {
      id: 'frontend',
      roleFamilyId: 'software-engineering',
      name: 'Frontend Engineer',
      stacks: [
        { id: 'react', name: 'React' },
        { id: 'nextjs', name: 'Next.js' },
      ],
    },
    {
      id: 'backend',
      roleFamilyId: 'software-engineering',
      name: 'Backend Engineer',
      stacks: [
        { id: 'nodejs', name: 'Node.js' },
        { id: 'python', name: 'Python' },
      ],
    },
    {
      id: 'fullstack',
      roleFamilyId: 'software-engineering',
      name: 'Fullstack Engineer',
      stacks: [
        { id: 'react', name: 'React' },
        { id: 'nextjs', name: 'Next.js' },
        { id: 'nodejs', name: 'Node.js' },
      ],
    },
    { id: 'hr-ma-manager', roleFamilyId: 'm-and-a', name: 'HR M&A Manager', stacks: [] },
  ],
  questions: [
    // Universal
    {
      id: 'U-01',
      text: 'Tell me about yourself.',
      type: 'role-specific',
      level: 'all',
      scope: {},
      tips: {
        asking: 'Can you tell a focused story that leads to this role?',
        hit: 'Present → past → why this job, in under two minutes.',
        avoid: 'Reciting your CV line by line.',
      },
      status: 'approved',
    },
    {
      id: 'U-02',
      text: 'Tell me about a time you disagreed with a teammate or manager.',
      type: 'behavioural',
      level: 'all',
      scope: {},
      tips: {
        asking: 'Can you push back respectfully and still commit?',
        hit: 'STAR, the data you used, how you landed it, the relationship afterwards.',
        avoid: 'Making the other person the villain.',
      },
      status: 'approved',
    },
    {
      id: 'U-03',
      text: 'Describe a time you failed or made a significant mistake.',
      type: 'behavioural',
      level: 'all',
      scope: {},
      tips: {
        asking: 'Self-awareness and ownership.',
        hit: "A real mistake, what you did immediately, what you changed so it won't recur.",
        avoid: 'A disguised strength ("I work too hard").',
      },
      status: 'approved',
    },
    {
      id: 'U-07',
      text: 'Why do you want to work here?',
      type: 'culture-fit',
      level: 'all',
      scope: {},
      tips: {
        asking: 'Did you do your homework, and will you stay?',
        hit: 'Two or three specifics about the company tied to your goals.',
        avoid: 'Generic praise or salary.',
      },
      status: 'approved',
    },
    // Frontend fundamentals
    {
      id: 'FE-01',
      text: "Explain the JavaScript event loop. What's the difference between microtasks and macrotasks?",
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'frontend' },
      tips: {
        asking: 'Do you understand async execution order?',
        hit: 'Call stack, task queue, microtask queue drains first (promises), a short ordering example.',
        avoid: 'Saying JS is multi-threaded.',
      },
      status: 'approved',
    },
    {
      id: 'FE-03',
      text: 'Walk me through what happens from typing a URL to the page being interactive.',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'frontend' },
      tips: {
        asking: 'Breadth across network and browser.',
        hit: 'DNS, TCP/TLS, HTTP, HTML parse, CSSOM, render tree, layout, paint, JS hydration.',
        avoid: 'Going deep on one step and skipping the rest.',
      },
      status: 'approved',
    },
    {
      id: 'FE-06',
      text: 'How do you make a custom dropdown or modal accessible?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'frontend' },
      tips: {
        asking: 'Real accessibility practice.',
        hit: 'Semantic HTML first, ARIA roles, focus trap and return, keyboard support, screen-reader testing.',
        avoid: '"Add aria-label" as the whole answer.',
      },
      status: 'approved',
    },
    // React
    {
      id: 'RE-01',
      text: 'How does React decide when to re-render a component?',
      type: 'technical',
      level: 'entry',
      scope: {
        industryId: 'technology',
        roleFamilyId: 'software-engineering',
        stack: 'react',
      },
      tips: {
        asking: 'Your mental model of rendering.',
        hit: 'State, props or context change, parent re-render, reconciliation, render vs commit.',
        avoid: 'Confusing a re-render with a DOM update.',
      },
      status: 'approved',
      version: 'react@19',
    },
    {
      id: 'RE-03',
      text: 'Explain useEffect. What are common mistakes with it?',
      type: 'technical',
      level: 'entry',
      scope: {
        industryId: 'technology',
        roleFamilyId: 'software-engineering',
        stack: 'react',
      },
      tips: {
        asking: 'Effects as synchronisation, not lifecycle.',
        hit: 'Dependency array, cleanup, "you might not need an effect" (derive state, event handlers).',
        avoid: 'Fetching in effects with no cleanup or race handling.',
      },
      status: 'approved',
      version: 'react@19',
    },
    {
      id: 'RE-08',
      text: 'A page in your React app feels slow. How do you investigate?',
      type: 'situational',
      level: 'mid',
      scope: {
        industryId: 'technology',
        roleFamilyId: 'software-engineering',
        stack: 'react',
      },
      tips: {
        asking: 'Your debugging process.',
        hit: 'Reproduce, React Profiler and Performance tab, find the cause, fix, measure again.',
        avoid: 'Jumping straight to memoisation.',
      },
      status: 'approved',
    },
    // Next.js
    {
      id: 'NX-03',
      text: 'When should a component be a Server Component vs a Client Component?',
      type: 'technical',
      level: 'mid',
      scope: {
        industryId: 'technology',
        roleFamilyId: 'software-engineering',
        stack: 'nextjs',
      },
      tips: {
        asking: 'Boundary design.',
        hit: 'Default to server, "use client" for interactivity and browser APIs, push the boundary down.',
        avoid: '"use client" at the top of every file.',
      },
      status: 'approved',
    },
    {
      id: 'NX-04',
      text: 'What are Server Actions and what are their risks?',
      type: 'technical',
      level: 'mid',
      scope: {
        industryId: 'technology',
        roleFamilyId: 'software-engineering',
        stack: 'nextjs',
      },
      tips: {
        asking: 'Mutations and security.',
        hit: "They're public endpoints: validate input and authorise every call, revalidate after.",
        avoid: "Assuming they're private because they live in server code.",
      },
      status: 'approved',
    },
    // Frontend system design
    {
      id: 'SD-01',
      text: 'Design the frontend for an infinite-scrolling news feed.',
      type: 'technical',
      level: 'senior',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'frontend' },
      tips: {
        asking: 'Structured frontend system design.',
        hit: 'Requirements first, component tree, pagination, virtualisation, caching, error states, accessibility.',
        avoid: 'Jumping into code before clarifying scope.',
      },
      status: 'approved',
    },
    {
      id: 'SD-06',
      text: 'A release broke checkout for some users. Walk me through your response.',
      type: 'situational',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'frontend' },
      tips: {
        asking: 'Incident handling.',
        hit: 'Assess scope, roll back or flag off first, communicate, root cause, post-mortem.',
        avoid: 'Debugging live before stopping the impact.',
      },
      status: 'approved',
    },
    // Software engineering (every engineering role)
    {
      id: 'SE-01',
      text: 'How do you approach reviewing a teammate’s pull request?',
      type: 'role-specific',
      level: 'all',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering' },
      tips: {
        asking: 'Collaboration and code quality judgement.',
        hit: 'Understand intent first, correctness and risk over style, kind and specific comments, approve when good enough.',
        avoid: 'Nitpicking formatting a linter should catch.',
      },
      status: 'approved',
    },
    {
      id: 'SE-02',
      text: 'How do you decide what to test, and at which level?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering' },
      tips: {
        asking: 'A pragmatic testing strategy.',
        hit: 'Test behaviour not implementation, unit vs integration vs end-to-end trade-offs, cover the risky paths.',
        avoid: 'Chasing 100% coverage as the goal.',
      },
      status: 'approved',
    },
    // Backend fundamentals
    {
      id: 'BE-01',
      text: 'Design a REST API for a to-do app. How do you handle versioning and errors?',
      type: 'technical',
      level: 'entry',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'backend' },
      tips: {
        asking: 'Resource modelling and HTTP fluency.',
        hit: 'Nouns as resources, correct verbs and status codes, consistent error shape, a versioning strategy.',
        avoid: 'Verbs in URLs and 200 OK for every response.',
      },
      status: 'approved',
    },
    {
      id: 'BE-02',
      text: 'What is a database index, and when can one hurt?',
      type: 'technical',
      level: 'entry',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'backend' },
      tips: {
        asking: 'Database fundamentals.',
        hit: 'B-tree lookup instead of a full scan, composite index column order, slower writes and extra storage.',
        avoid: '"Index every column."',
      },
      status: 'approved',
    },
    {
      id: 'BE-03',
      text: 'Explain transaction isolation levels. What anomalies does each prevent?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'backend' },
      tips: {
        asking: 'Concurrency correctness.',
        hit: 'Dirty reads, non-repeatable reads, phantoms; read committed vs repeatable read vs serializable; the cost of each.',
        avoid: 'Assuming the default level makes everything safe.',
      },
      status: 'approved',
    },
    {
      id: 'BE-04',
      text: 'How would you make a payment endpoint safe to retry?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'backend' },
      tips: {
        asking: 'Idempotency in distributed systems.',
        hit: 'Client-supplied idempotency key, store the result, return it on repeats, handle concurrent duplicates.',
        avoid: 'Relying on the client never retrying.',
      },
      status: 'approved',
    },
    {
      id: 'BE-05',
      text: 'An API endpoint’s p99 latency has doubled since yesterday. How do you investigate?',
      type: 'situational',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'backend' },
      tips: {
        asking: 'Methodical production debugging.',
        hit: 'Check what changed (deploys, traffic, data), traces and slow-query logs, isolate the layer, fix and verify.',
        avoid: 'Adding a cache before finding the cause.',
      },
      status: 'approved',
    },
    {
      id: 'BE-06',
      text: 'Design a URL shortener that handles 10,000 redirects per second.',
      type: 'technical',
      level: 'senior',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'backend' },
      tips: {
        asking: 'Structured backend system design.',
        hit: 'Requirements and scale estimates, ID generation, storage choice, caching hot links, read/write split, analytics.',
        avoid: 'Drawing boxes before agreeing on requirements.',
      },
      status: 'approved',
    },
    // Node.js
    {
      id: 'ND-01',
      text: 'Why is blocking the event loop a problem in Node.js, and how do you avoid it?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', stack: 'nodejs' },
      tips: {
        asking: 'The Node concurrency model.',
        hit: 'One thread runs JS, so CPU work stalls every request; use async I/O, worker threads or a job queue.',
        avoid: 'Saying async/await makes CPU-heavy code non-blocking.',
      },
      status: 'approved',
    },
    {
      id: 'ND-02',
      text: 'How do you handle errors in an Express or Fastify app so one bad request can’t crash the server?',
      type: 'technical',
      level: 'entry',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', stack: 'nodejs' },
      tips: {
        asking: 'Robust error handling.',
        hit: 'Central error middleware, awaiting every promise, unhandled rejection handling, safe messages to clients.',
        avoid: 'Swallowing errors or leaking stack traces.',
      },
      status: 'approved',
    },
    // Python
    {
      id: 'PY-01',
      text: 'What is the GIL, and how does it affect concurrency in Python?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', stack: 'python' },
      tips: {
        asking: 'Python’s concurrency trade-offs.',
        hit: 'One thread runs bytecode at a time; threads or asyncio suit I/O, multiprocessing suits CPU work.',
        avoid: 'Saying Python can’t do concurrency at all.',
      },
      status: 'approved',
    },
    {
      id: 'PY-02',
      text: 'When would you choose FastAPI over Django, or the other way round?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', stack: 'python' },
      tips: {
        asking: 'Framework judgement.',
        hit: 'Django for batteries-included apps (ORM, admin, auth); FastAPI for typed, async APIs; team and ecosystem fit.',
        avoid: 'Picking one on hype alone.',
      },
      status: 'approved',
    },
    // Fullstack
    {
      id: 'FS-01',
      text: 'Walk me through building a feature end to end, from database schema to UI.',
      type: 'role-specific',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'fullstack' },
      tips: {
        asking: 'Ownership across the stack.',
        hit: 'Clarify the requirement, schema and migration, API contract, UI states, tests, rollout behind a flag.',
        avoid: 'Treating either the frontend or the backend as an afterthought.',
      },
      status: 'approved',
    },
    {
      id: 'FS-02',
      text: 'How would you implement authentication for a web app with a separate API?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'fullstack' },
      tips: {
        asking: 'Security across the client–server boundary.',
        hit: 'Session cookies vs tokens, HttpOnly and SameSite, CSRF, token refresh, authorising on the server every time.',
        avoid: 'Storing long-lived tokens in localStorage without discussing the risk.',
      },
      status: 'approved',
    },
    {
      id: 'FS-03',
      text: 'Where should validation live: the client, the server or both?',
      type: 'technical',
      level: 'entry',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'fullstack' },
      tips: {
        asking: 'Trust boundaries.',
        hit: 'Client for fast feedback, server as the source of truth, a shared schema so the two can’t drift.',
        avoid: 'Trusting client-side validation alone.',
      },
      status: 'approved',
    },
    {
      id: 'FS-04',
      text: 'Users see stale data after saving a form. How do you track down the cause?',
      type: 'situational',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'fullstack' },
      tips: {
        asking: 'Debugging across caches and layers.',
        hit: 'Confirm the write landed, then check each cache: client state, HTTP or CDN cache, server cache, read replicas.',
        avoid: 'Blaming the browser cache without evidence.',
      },
      status: 'approved',
    },
    {
      id: 'FS-05',
      text: 'Design a real-time collaborative comments feature for a document app.',
      type: 'technical',
      level: 'senior',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'fullstack' },
      tips: {
        asking: 'End-to-end system design.',
        hit: 'Data model, WebSockets vs polling, optimistic UI, ordering and conflicts, presence, scaling the fan-out.',
        avoid: 'Ignoring the offline and reconnect cases.',
      },
      status: 'approved',
    },
    // People in Deals: HR M&A Manager
    // Role and motivation
    {
      id: 'MP-01',
      text: 'Why HR in M&A, rather than a generalist HR or consulting role?',
      type: 'role-specific',
      level: 'all',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Genuine, informed motivation for the people side of deals.',
        hit: 'What draws you to transactions, a specific deal or project that sparked it, how people issues make or break deal value, what you bring from HR or consulting.',
        avoid: 'Generic interest in "strategy" or treating HR as a back-office afterthought.',
      },
      status: 'approved',
    },
    {
      id: 'MP-02',
      text: 'Where does HR add value across the deal lifecycle, from pre-sign to post-close?',
      type: 'role-specific',
      level: 'mid',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Do you see the whole deal, not just Day 1?',
        hit: 'Pre-sign: HR due diligence, people costs and risks in price and SPA protections; sign-to-close: Day 1 planning, consultation, org design, retention, TSAs; post-close: integration or standalone set-up, harmonisation, culture, synergy delivery.',
        avoid: 'Describing only the integration phase.',
      },
      status: 'approved',
    },
    // Deal structure and labour law
    {
      id: 'LR-01',
      text: 'How does the people approach differ between a share deal and an asset deal?',
      type: 'technical',
      level: 'entry',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Deal literacy: the legal mechanism drives everything else.',
        hit: 'Share deal: employer entity is unchanged so employees, contracts and liabilities stay put; asset deal: employees move to a new employer, automatically under TUPE or the Acquired Rights Directive in the UK and EU, by offer and acceptance elsewhere; consent, consultation, benefits replication and timeline all differ.',
        avoid: 'Saying employees always need to consent to move.',
      },
      status: 'approved',
    },
    {
      id: 'LR-02',
      text: 'Explain TUPE. What must the seller and buyer do, and what can the buyer change after the transfer?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'UK employee transfer law in practice.',
        hit: 'Employees assigned to the undertaking transfer automatically on existing terms with continuity of service; duty to inform and consult appropriate representatives; employee liability information at least 28 days before transfer; changes or dismissals because of the transfer are void or unfair unless there is an ETO reason; occupational pensions are treated differently.',
        avoid: 'Assuming the buyer can harmonise terms on Day 1.',
      },
      status: 'approved',
    },
    {
      id: 'LR-03',
      text: 'Your buyer wants to sign in six weeks, but the target has a Dutch works council. What do you advise?',
      type: 'situational',
      level: 'mid',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Labour relations as a critical-path item, not a formality.',
        hit: 'Works council advice is mandatory before the decision is final, so request it while it can still influence the decision; a written request with the reasons, consequences for employees and planned measures; realistically two to three months; a one-month waiting period if advice is negative; build it into the signing timeline and agree process with the works council early.',
        avoid: 'Signing first and informing the works council afterwards.',
      },
      status: 'approved',
    },
    // HR due diligence
    {
      id: 'DD-01',
      text: 'What do you look for in HR due diligence, and how can findings affect the deal price or the SPA?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Linking people findings to value.',
        hit: 'Change-of-control and key executive arrangements, pension deficits and other debt-like items such as accrued bonuses and holiday, quality of earnings adjustments for compensation, severance and restructuring costs, retention risk, labour relations and litigation, worker misclassification; reflect findings in price, debt-like adjustments, indemnities or conditions.',
        avoid: 'A checklist of HR documents with no link to value or deal protections.',
      },
      status: 'approved',
    },
    {
      id: 'DD-02',
      text: 'In due diligence you find the target’s median gender pay gap is 11%. What do you tell the buyer?',
      type: 'situational',
      level: 'mid',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Regulatory awareness turned into a deal recommendation.',
        hit: 'It exceeds the 5% threshold in the EU Pay Transparency Directive, which can trigger a joint pay assessment and corrective action; check data quality and whether gaps are objectively justified; estimate remediation cost and back-pay exposure; reflect it in price, indemnities or the integration plan; note reporting deadlines from 2027.',
        avoid: 'Treating it as a reputational issue only, with no cost or legal angle.',
      },
      status: 'approved',
    },
    {
      id: 'DD-03',
      text: 'What is a clean team, and when do you need one for HR data?',
      type: 'technical',
      level: 'entry',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Competition law and data privacy before close.',
        hit: 'Until close the parties must act as independent competitors, so commercially sensitive data such as individual pay goes only to a ring-fenced clean team; protocols on who sees what; aggregated or anonymised outputs to the wider team; GDPR and data minimisation.',
        avoid: 'Sharing full employee census files between buyer and seller before close.',
      },
      status: 'approved',
    },
    // Separation and carve-out
    {
      id: 'CO-01',
      text: 'Which HR services typically go on a transitional services agreement, and how do you plan the exit?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Practical TSA experience.',
        hit: 'Typical services: payroll, benefits administration, HRIS and data, HR operations and helpdesk, global mobility; define each service with scope, service levels, cost and duration; a change process through joint governance; an exit plan per service agreed from the start; keep TSAs as short as possible.',
        avoid: 'Treating the TSA as a single block with one end date and no exit plan.',
      },
      status: 'approved',
    },
    {
      id: 'CO-02',
      text: 'What are stranded costs in a separation, and how can HR help reduce them?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Commercial thinking from the seller’s side.',
        hit: 'Costs left with the seller once the business and its revenue leave, such as shared-service and HR headcount; transfer seller staff into the buyer’s vacancies, redeploy, right-size the remaining function, price the TSA to recover cost, and plan timing around consultation.',
        avoid: 'Seeing stranded cost only as a finance topic.',
      },
      status: 'approved',
    },
    {
      id: 'CO-03',
      text: 'What does a good HR Day 1 look like for a newly separated business?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Can you prioritise what truly must work on Day 1?',
        hit: 'Everyone paid correctly and on time, benefits and insurance in place, the right legal employer and contracts or transfer letters, managers and reporting lines, systems access, key policies, clear communications and FAQs, a helpdesk; separate the must-haves from what can wait until after Day 1.',
        avoid: 'Trying to deliver the end-state operating model on Day 1.',
      },
      status: 'approved',
    },
    // Integration
    {
      id: 'PM-01',
      text: 'How do you approach harmonising compensation and benefits after a merger?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'A structured, compliant approach to a sensitive topic.',
        hit: 'Side-by-side analysis of both packages, agree a reward strategy, check legal constraints such as collective agreements and transfer protections, design scenarios with cost impact, consult works councils and unions, use transition tools like grandfathering or red-circling, communicate clearly, and do sensitive pre-close work in a clean team.',
        avoid: 'Levelling everyone up to the richer package without costing it.',
      },
      status: 'approved',
    },
    {
      id: 'PM-02',
      text: 'The deal case assumes 10% headcount synergies. How would you validate and deliver that number?',
      type: 'technical',
      level: 'senior',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Can you connect workforce analytics to the synergy case?',
        hit: 'Baseline census and fully loaded cost, analyse duplication by function, location, spans and layers, check legal and consultation timelines and one-off costs such as severance, assess retention risk to critical roles, phase delivery, and track realisation against the baseline.',
        avoid: 'Accepting the top-down number without testing feasibility and timing.',
      },
      status: 'approved',
    },
    {
      id: 'PM-03',
      text: 'How should the integration approach change how much you invest in culture?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Tailoring culture work to the deal, not one size fits all.',
        hit: 'Absorption needs moderate intervention to avoid talent loss, best of both needs the most because it is hardest to deliver, a stand-alone target needs little; diagnose similarities and differences, define the few behaviours that matter, build a roadmap, track it with culture measures, and make leaders accountable.',
        avoid: 'Proposing culture surveys and values workshops regardless of deal type.',
      },
      status: 'approved',
    },
    // Talent, org design and retention
    {
      id: 'TR-01',
      text: 'How would you design a key talent retention programme for a carve-out?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Targeted, governed retention, not blanket bonuses.',
        hit: 'Identify critical roles and knowledge holders early, categorise roles by retention need, set clear eligibility and a governed budget, use cash awards paid in instalments tied to milestones, combine with non-financial levers such as career opportunities and recognition, agree letters before announcement, and track retention after close.',
        avoid: 'Offering everyone the same retention bonus.',
      },
      status: 'approved',
    },
    {
      id: 'TR-02',
      text: 'How would you run selection into the new organisation structure fairly and quickly?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Org design and selection under deal pressure.',
        hit: 'Agree design principles, map current roles to the new structure, decide which roles are matched and which go to selection, use objective criteria with calibration across both companies, appoint leadership first and then in waves, consult where required, and communicate decisions transparently.',
        avoid: 'Defaulting to the acquirer’s people or selecting on tenure.',
      },
      status: 'approved',
    },
    // Change, communications and programme management
    {
      id: 'CC-01',
      text: 'What should employees in a business being sold hear on announcement day?',
      type: 'situational',
      level: 'entry',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Clear, legally careful change communication.',
        hit: 'Why the sale is happening, what changes and what does not, the expected timeline, what happens next and when they will hear more, where to ask questions; brief managers first with talking points and FAQs; respect consultation obligations so nothing is presented as already decided.',
        avoid: 'Promising that nothing will change.',
      },
      status: 'approved',
    },
    {
      id: 'CC-02',
      text: 'A country HR team keeps missing separation milestones and its HR director is on leave. What do you do?',
      type: 'situational',
      level: 'mid',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Programme management and stakeholder judgement.',
        hit: 'Understand the root cause first, check the impact on the critical path, give hands-on support or extra resource, find an interim decision-maker, escalate through the programme governance with options, update the risk log, and keep reporting transparent.',
        avoid: 'Escalating straight to the steering committee without understanding the cause.',
      },
      status: 'approved',
    },
    {
      id: 'CC-03',
      text: 'Tell me about a time you managed a demanding senior stakeholder on a project with a fixed deadline.',
      type: 'behavioural',
      level: 'mid',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Consulting presence in a transaction environment.',
        hit: 'STAR, how you understood what the stakeholder needed, how you challenged or reset expectations with evidence, how you kept the deadline, and what the relationship looked like afterwards.',
        avoid: 'A story where you simply did whatever the stakeholder asked.',
      },
      status: 'approved',
    },
    {
      id: 'CC-04',
      text: 'Why do so many deals fail to deliver their expected value, and what is HR’s part in that?',
      type: 'curveball',
      level: 'all',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Critical thinking about people risk.',
        hit: 'Culture clash, loss of key talent, slow or unclear leadership decisions, poor communication, overestimated synergies, and underestimated integration costs; HR can reduce each through diligence, retention, early org decisions, change management and tracking.',
        avoid: 'Giving only one reason.',
      },
      status: 'approved',
    },
    // Case studies
    {
      id: 'CS-01',
      text: 'Case study: a global consumer goods group is selling its tea business (about 20,000 employees in 40+ countries) to a private equity buyer. The business relies on the seller’s HR systems and services, 1,000+ roles must be filled within six months, and local HR has little carve-out experience. You lead the HR workstream. Walk me through your approach.',
      type: 'case-study',
      level: 'mid',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Can you structure a large, entangled carve-out end to end?',
        hit: 'Confirm the perimeter and in-scope census, the legal transfer mechanism and consultation needs per country, a recruitment plan that prioritises Day 1-critical roles and hires seller staff to cut stranded cost, standalone benefits and policies market by market, HR TSAs for payroll and systems, governance and a programme office, and support for an inexperienced local HR team.',
        avoid: 'Jumping into one workstream such as recruitment without framing the whole programme.',
        exampleOutline: [
          'Clarify: deal timeline, share or asset deal per country, buyer’s plans, what is already standalone',
          'Perimeter: who is in scope, data quality, legal entities',
          'Workstreams: labour relations, org design and recruitment, reward and benefits, policies, HR systems and payroll, HR operating model',
          'Critical path: consultation timelines, Day 1 must-haves, recruitment ramp-up',
          'Governance: HR programme office, weekly reporting, risk log, escalation to the steering committee',
          'Value: stranded cost mitigation, TSA scope and exit, lean future HR function',
        ],
      },
      status: 'approved',
    },
    {
      id: 'CS-02',
      text: 'Case study: your client is carving out a software business with about 1,600 employees in 33 countries, needing 52 local transactions, while also replacing its HR system. What does your Day 1 HR readiness plan look like?',
      type: 'case-study',
      level: 'mid',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Multi-country separation planning under parallel change.',
        hit: 'A top-level separation plan and critical path, workstreams for labour relations, org design and recruitment, transition, reward and pensions, policies, data and HR operations, legal entity readiness, country-by-country consultation, logically separating the HR system for Day 1 before cutover, HR TSAs for an interim period, and tracking risks and dependencies.',
        avoid: 'Ignoring the clash between the system implementation and the Day 1 date.',
        exampleOutline: [
          'Map the 52 transactions by country, type and date',
          'Set Day 1 must-haves per country: employer, payroll, benefits, contracts',
          'Decide the HR system approach: separate the old system for Day 1 or go live first',
          'Plan consultation and employee information country by country',
          'Agree TSAs for the remaining gaps, with exit dates',
          'Run a programme office with weekly country status and a risk log',
        ],
      },
      status: 'approved',
    },
    {
      id: 'CS-03',
      text: 'Case study: you need to move 6,000 employees across 42 territories into a newly separated business, through 9 share sales and 33 asset sales, in under nine months. How do you design the employee transfer process?',
      type: 'case-study',
      level: 'mid',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Running a global employee transfer at scale.',
        hit: 'Define the legal transfer route per territory with counsel, automatic transfer or offer and acceptance, plan consultation with unions and works councils before signing where needed, build one source of truth for employee data, standardise letters and track acceptances on a dashboard, design the employee experience and communications, escalate issues quickly, and line up Day 1 payroll and benefits.',
        avoid: 'Treating all 42 territories the same.',
        exampleOutline: [
          'Segment territories: share sale, automatic asset transfer, offer and acceptance',
          'Work with counsel on the process and timeline for each segment',
          'Consult employee representatives where required',
          'Issue letters and track acceptances centrally',
          'Communicate early and give employees a place to ask questions',
          'Report weekly progress and escalate blockers through governance',
        ],
      },
      status: 'approved',
    },
    {
      id: 'CS-04',
      text: 'Case study: a company will demerge a 30,000-person consumer division and list it on the stock exchange within three years. As the people lead, what are your priorities on the road to the listing?',
      type: 'case-study',
      level: 'senior',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'People strategy for a separation and IPO.',
        hit: 'Design the people operating model for both the new company and the remaining company, appoint and align the leadership team early, set executive reward and long-term incentives fit for a listed company, set up remuneration governance, retain key talent through the separation, meet efficiency expectations investors will test, manage labour relations and culture, and communicate consistently.',
        avoid: 'Focusing only on the legal separation and forgetting what being a listed company requires.',
        exampleOutline: [
          'Prepare the company: HR strategy, policies, governance, labour relations',
          'Prepare the people: leadership appointments, talent and retention, culture',
          'Going public: executive reward, disclosures, remuneration committee',
          'Being public: long-term incentives, workforce KPIs investors care about, engagement',
        ],
      },
      status: 'approved',
    },
    {
      id: 'CS-05',
      text: 'Case study: you are supporting a seller’s HR team through a competitive sale of one of its businesses to private equity bidders. How do you run the HR workstream from the bidding phase to TSA exit?',
      type: 'case-study',
      level: 'mid',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Sell-side HR from first bid to final exit.',
        hit: 'Prepare HR vendor due diligence and the data room, answer bidder HR questions and run deep-dive sessions, design a lean standalone HR operating model benchmarked against peers, plan separation including consultation and recruitment, scope and cost the HR TSAs, track employees moving across, and manage TSA exit while keeping relations with the buyer constructive.',
        avoid: 'Treating the sale process as finance’s job and starting HR work after signing.',
        exampleOutline: [
          'Bid phase: HR data room, vendor due diligence, bidder questions and sessions',
          'Design: standalone HR operating model and its cost',
          'Sign to close: separation plan, consultation, recruitment, TSA scope and pricing',
          'Post close: run the TSAs, track employee moves, exit each service on time',
        ],
      },
      status: 'approved',
    },
  ],
};
