import type { Content } from './schema.ts';

/**
 * Development seed. Used when Sanity isn't configured, so the app runs out of the box.
 * The real question bank lives in Sanity; import the full pilot bank with `npm run import:bank`.
 */
export const seedContent: Content = {
  industries: [
    {
      id: 'technology',
      name: 'Technology',
      color: '#6B3BFF',
      blurb: 'Engineering roles, from fundamentals to framework deep-dives.',
    },
    {
      id: 'm-and-a',
      name: 'Mergers & Acquisitions',
      color: '#00A676',
      blurb: 'Deal teams in banking, transaction services and corporate development.',
    },
  ],
  roleFamilies: [
    { id: 'software-engineering', industryId: 'technology', name: 'Software Engineering' },
    { id: 'm-and-a', industryId: 'm-and-a', name: 'M&A' },
  ],
  specialisations: [
    {
      id: 'frontend',
      roleFamilyId: 'software-engineering',
      name: 'Frontend Engineer',
      stacks: [
        { id: 'react', name: 'React' },
        { id: 'nextjs', name: 'Next.js' },
      ],
    },
    {
      id: 'backend',
      roleFamilyId: 'software-engineering',
      name: 'Backend Engineer',
      stacks: [
        { id: 'nodejs', name: 'Node.js' },
        { id: 'python', name: 'Python' },
      ],
    },
    {
      id: 'fullstack',
      roleFamilyId: 'software-engineering',
      name: 'Fullstack Engineer',
      stacks: [
        { id: 'react', name: 'React' },
        { id: 'nextjs', name: 'Next.js' },
        { id: 'nodejs', name: 'Node.js' },
      ],
    },
    { id: 'ma-analyst', roleFamilyId: 'm-and-a', name: 'M&A Analyst', stacks: [] },
    { id: 'ma-associate', roleFamilyId: 'm-and-a', name: 'M&A Associate', stacks: [] },
    { id: 'corp-dev', roleFamilyId: 'm-and-a', name: 'Corporate Development Manager', stacks: [] },
  ],
  questions: [
    // Universal
    {
      id: 'U-01',
      text: 'Tell me about yourself.',
      type: 'role-specific',
      level: 'all',
      scope: {},
      tips: {
        asking: 'Can you tell a focused story that leads to this role?',
        hit: 'Present → past → why this job, in under two minutes.',
        avoid: 'Reciting your CV line by line.',
      },
      status: 'approved',
    },
    {
      id: 'U-02',
      text: 'Tell me about a time you disagreed with a teammate or manager.',
      type: 'behavioural',
      level: 'all',
      scope: {},
      tips: {
        asking: 'Can you push back respectfully and still commit?',
        hit: 'STAR, the data you used, how you landed it, the relationship afterwards.',
        avoid: 'Making the other person the villain.',
      },
      status: 'approved',
    },
    {
      id: 'U-03',
      text: 'Describe a time you failed or made a significant mistake.',
      type: 'behavioural',
      level: 'all',
      scope: {},
      tips: {
        asking: 'Self-awareness and ownership.',
        hit: "A real mistake, what you did immediately, what you changed so it won't recur.",
        avoid: 'A disguised strength ("I work too hard").',
      },
      status: 'approved',
    },
    {
      id: 'U-07',
      text: 'Why do you want to work here?',
      type: 'culture-fit',
      level: 'all',
      scope: {},
      tips: {
        asking: 'Did you do your homework, and will you stay?',
        hit: 'Two or three specifics about the company tied to your goals.',
        avoid: 'Generic praise or salary.',
      },
      status: 'approved',
    },
    // Frontend fundamentals
    {
      id: 'FE-01',
      text: "Explain the JavaScript event loop. What's the difference between microtasks and macrotasks?",
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'frontend' },
      tips: {
        asking: 'Do you understand async execution order?',
        hit: 'Call stack, task queue, microtask queue drains first (promises), a short ordering example.',
        avoid: 'Saying JS is multi-threaded.',
      },
      status: 'approved',
    },
    {
      id: 'FE-03',
      text: 'Walk me through what happens from typing a URL to the page being interactive.',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'frontend' },
      tips: {
        asking: 'Breadth across network and browser.',
        hit: 'DNS, TCP/TLS, HTTP, HTML parse, CSSOM, render tree, layout, paint, JS hydration.',
        avoid: 'Going deep on one step and skipping the rest.',
      },
      status: 'approved',
    },
    {
      id: 'FE-06',
      text: 'How do you make a custom dropdown or modal accessible?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'frontend' },
      tips: {
        asking: 'Real accessibility practice.',
        hit: 'Semantic HTML first, ARIA roles, focus trap and return, keyboard support, screen-reader testing.',
        avoid: '"Add aria-label" as the whole answer.',
      },
      status: 'approved',
    },
    // React
    {
      id: 'RE-01',
      text: 'How does React decide when to re-render a component?',
      type: 'technical',
      level: 'entry',
      scope: {
        industryId: 'technology',
        roleFamilyId: 'software-engineering',
        stack: 'react',
      },
      tips: {
        asking: 'Your mental model of rendering.',
        hit: 'State, props or context change, parent re-render, reconciliation, render vs commit.',
        avoid: 'Confusing a re-render with a DOM update.',
      },
      status: 'approved',
      version: 'react@19',
    },
    {
      id: 'RE-03',
      text: 'Explain useEffect. What are common mistakes with it?',
      type: 'technical',
      level: 'entry',
      scope: {
        industryId: 'technology',
        roleFamilyId: 'software-engineering',
        stack: 'react',
      },
      tips: {
        asking: 'Effects as synchronisation, not lifecycle.',
        hit: 'Dependency array, cleanup, "you might not need an effect" (derive state, event handlers).',
        avoid: 'Fetching in effects with no cleanup or race handling.',
      },
      status: 'approved',
      version: 'react@19',
    },
    {
      id: 'RE-08',
      text: 'A page in your React app feels slow. How do you investigate?',
      type: 'situational',
      level: 'mid',
      scope: {
        industryId: 'technology',
        roleFamilyId: 'software-engineering',
        stack: 'react',
      },
      tips: {
        asking: 'Your debugging process.',
        hit: 'Reproduce, React Profiler and Performance tab, find the cause, fix, measure again.',
        avoid: 'Jumping straight to memoisation.',
      },
      status: 'approved',
    },
    // Next.js
    {
      id: 'NX-03',
      text: 'When should a component be a Server Component vs a Client Component?',
      type: 'technical',
      level: 'mid',
      scope: {
        industryId: 'technology',
        roleFamilyId: 'software-engineering',
        stack: 'nextjs',
      },
      tips: {
        asking: 'Boundary design.',
        hit: 'Default to server, "use client" for interactivity and browser APIs, push the boundary down.',
        avoid: '"use client" at the top of every file.',
      },
      status: 'approved',
    },
    {
      id: 'NX-04',
      text: 'What are Server Actions and what are their risks?',
      type: 'technical',
      level: 'mid',
      scope: {
        industryId: 'technology',
        roleFamilyId: 'software-engineering',
        stack: 'nextjs',
      },
      tips: {
        asking: 'Mutations and security.',
        hit: "They're public endpoints: validate input and authorise every call, revalidate after.",
        avoid: "Assuming they're private because they live in server code.",
      },
      status: 'approved',
    },
    // Frontend system design
    {
      id: 'SD-01',
      text: 'Design the frontend for an infinite-scrolling news feed.',
      type: 'technical',
      level: 'senior',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'frontend' },
      tips: {
        asking: 'Structured frontend system design.',
        hit: 'Requirements first, component tree, pagination, virtualisation, caching, error states, accessibility.',
        avoid: 'Jumping into code before clarifying scope.',
      },
      status: 'approved',
    },
    {
      id: 'SD-06',
      text: 'A release broke checkout for some users. Walk me through your response.',
      type: 'situational',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'frontend' },
      tips: {
        asking: 'Incident handling.',
        hit: 'Assess scope, roll back or flag off first, communicate, root cause, post-mortem.',
        avoid: 'Debugging live before stopping the impact.',
      },
      status: 'approved',
    },
    // Software engineering (every engineering role)
    {
      id: 'SE-01',
      text: 'How do you approach reviewing a teammate’s pull request?',
      type: 'role-specific',
      level: 'all',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering' },
      tips: {
        asking: 'Collaboration and code quality judgement.',
        hit: 'Understand intent first, correctness and risk over style, kind and specific comments, approve when good enough.',
        avoid: 'Nitpicking formatting a linter should catch.',
      },
      status: 'approved',
    },
    {
      id: 'SE-02',
      text: 'How do you decide what to test, and at which level?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering' },
      tips: {
        asking: 'A pragmatic testing strategy.',
        hit: 'Test behaviour not implementation, unit vs integration vs end-to-end trade-offs, cover the risky paths.',
        avoid: 'Chasing 100% coverage as the goal.',
      },
      status: 'approved',
    },
    // Backend fundamentals
    {
      id: 'BE-01',
      text: 'Design a REST API for a to-do app. How do you handle versioning and errors?',
      type: 'technical',
      level: 'entry',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'backend' },
      tips: {
        asking: 'Resource modelling and HTTP fluency.',
        hit: 'Nouns as resources, correct verbs and status codes, consistent error shape, a versioning strategy.',
        avoid: 'Verbs in URLs and 200 OK for every response.',
      },
      status: 'approved',
    },
    {
      id: 'BE-02',
      text: 'What is a database index, and when can one hurt?',
      type: 'technical',
      level: 'entry',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'backend' },
      tips: {
        asking: 'Database fundamentals.',
        hit: 'B-tree lookup instead of a full scan, composite index column order, slower writes and extra storage.',
        avoid: '"Index every column."',
      },
      status: 'approved',
    },
    {
      id: 'BE-03',
      text: 'Explain transaction isolation levels. What anomalies does each prevent?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'backend' },
      tips: {
        asking: 'Concurrency correctness.',
        hit: 'Dirty reads, non-repeatable reads, phantoms; read committed vs repeatable read vs serializable; the cost of each.',
        avoid: 'Assuming the default level makes everything safe.',
      },
      status: 'approved',
    },
    {
      id: 'BE-04',
      text: 'How would you make a payment endpoint safe to retry?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'backend' },
      tips: {
        asking: 'Idempotency in distributed systems.',
        hit: 'Client-supplied idempotency key, store the result, return it on repeats, handle concurrent duplicates.',
        avoid: 'Relying on the client never retrying.',
      },
      status: 'approved',
    },
    {
      id: 'BE-05',
      text: 'An API endpoint’s p99 latency has doubled since yesterday. How do you investigate?',
      type: 'situational',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'backend' },
      tips: {
        asking: 'Methodical production debugging.',
        hit: 'Check what changed (deploys, traffic, data), traces and slow-query logs, isolate the layer, fix and verify.',
        avoid: 'Adding a cache before finding the cause.',
      },
      status: 'approved',
    },
    {
      id: 'BE-06',
      text: 'Design a URL shortener that handles 10,000 redirects per second.',
      type: 'technical',
      level: 'senior',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'backend' },
      tips: {
        asking: 'Structured backend system design.',
        hit: 'Requirements and scale estimates, ID generation, storage choice, caching hot links, read/write split, analytics.',
        avoid: 'Drawing boxes before agreeing on requirements.',
      },
      status: 'approved',
    },
    // Node.js
    {
      id: 'ND-01',
      text: 'Why is blocking the event loop a problem in Node.js, and how do you avoid it?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', stack: 'nodejs' },
      tips: {
        asking: 'The Node concurrency model.',
        hit: 'One thread runs JS, so CPU work stalls every request; use async I/O, worker threads or a job queue.',
        avoid: 'Saying async/await makes CPU-heavy code non-blocking.',
      },
      status: 'approved',
    },
    {
      id: 'ND-02',
      text: 'How do you handle errors in an Express or Fastify app so one bad request can’t crash the server?',
      type: 'technical',
      level: 'entry',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', stack: 'nodejs' },
      tips: {
        asking: 'Robust error handling.',
        hit: 'Central error middleware, awaiting every promise, unhandled rejection handling, safe messages to clients.',
        avoid: 'Swallowing errors or leaking stack traces.',
      },
      status: 'approved',
    },
    // Python
    {
      id: 'PY-01',
      text: 'What is the GIL, and how does it affect concurrency in Python?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', stack: 'python' },
      tips: {
        asking: 'Python’s concurrency trade-offs.',
        hit: 'One thread runs bytecode at a time; threads or asyncio suit I/O, multiprocessing suits CPU work.',
        avoid: 'Saying Python can’t do concurrency at all.',
      },
      status: 'approved',
    },
    {
      id: 'PY-02',
      text: 'When would you choose FastAPI over Django, or the other way round?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', stack: 'python' },
      tips: {
        asking: 'Framework judgement.',
        hit: 'Django for batteries-included apps (ORM, admin, auth); FastAPI for typed, async APIs; team and ecosystem fit.',
        avoid: 'Picking one on hype alone.',
      },
      status: 'approved',
    },
    // Fullstack
    {
      id: 'FS-01',
      text: 'Walk me through building a feature end to end, from database schema to UI.',
      type: 'role-specific',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'fullstack' },
      tips: {
        asking: 'Ownership across the stack.',
        hit: 'Clarify the requirement, schema and migration, API contract, UI states, tests, rollout behind a flag.',
        avoid: 'Treating either the frontend or the backend as an afterthought.',
      },
      status: 'approved',
    },
    {
      id: 'FS-02',
      text: 'How would you implement authentication for a web app with a separate API?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'fullstack' },
      tips: {
        asking: 'Security across the client–server boundary.',
        hit: 'Session cookies vs tokens, HttpOnly and SameSite, CSRF, token refresh, authorising on the server every time.',
        avoid: 'Storing long-lived tokens in localStorage without discussing the risk.',
      },
      status: 'approved',
    },
    {
      id: 'FS-03',
      text: 'Where should validation live: the client, the server or both?',
      type: 'technical',
      level: 'entry',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'fullstack' },
      tips: {
        asking: 'Trust boundaries.',
        hit: 'Client for fast feedback, server as the source of truth, a shared schema so the two can’t drift.',
        avoid: 'Trusting client-side validation alone.',
      },
      status: 'approved',
    },
    {
      id: 'FS-04',
      text: 'Users see stale data after saving a form. How do you track down the cause?',
      type: 'situational',
      level: 'mid',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'fullstack' },
      tips: {
        asking: 'Debugging across caches and layers.',
        hit: 'Confirm the write landed, then check each cache: client state, HTTP or CDN cache, server cache, read replicas.',
        avoid: 'Blaming the browser cache without evidence.',
      },
      status: 'approved',
    },
    {
      id: 'FS-05',
      text: 'Design a real-time collaborative comments feature for a document app.',
      type: 'technical',
      level: 'senior',
      scope: { industryId: 'technology', roleFamilyId: 'software-engineering', specialisationId: 'fullstack' },
      tips: {
        asking: 'End-to-end system design.',
        hit: 'Data model, WebSockets vs polling, optimistic UI, ordering and conflicts, presence, scaling the fan-out.',
        avoid: 'Ignoring the offline and reconnect cases.',
      },
      status: 'approved',
    },
    // M&A
    {
      id: 'MA-01',
      text: 'Why M&A, and why not another area of finance?',
      type: 'role-specific',
      level: 'entry',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Genuine, informed motivation.',
        hit: 'What draws you to deals, and a specific experience that sparked it.',
        avoid: '"It pays well" or a vague love of finance.',
      },
      status: 'approved',
    },
    {
      id: 'MA-02',
      text: 'Walk me through a recent deal you followed.',
      type: 'role-specific',
      level: 'entry',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Commercial awareness.',
        hit: 'Parties, size and structure, strategic rationale, synergies, your view on whether it makes sense.',
        avoid: "A deal you can't discuss beyond the headline.",
      },
      status: 'approved',
    },
    {
      id: 'AC-02',
      text: 'Depreciation goes up by £10. Walk me through the impact on the three statements.',
      type: 'technical',
      level: 'entry',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Mechanical fluency.',
        hit: 'Pre-tax income −10, net income −7.5 at 25% tax, cash +2.5, PP&E −10, retained earnings −7.5.',
        avoid: 'Forgetting the tax effect.',
      },
      status: 'approved',
    },
    {
      id: 'VA-02',
      text: 'Walk me through a DCF.',
      type: 'technical',
      level: 'entry',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'The most common technical question.',
        hit: 'Unlevered FCF, terminal value, discount at WACC, sum to EV, bridge to equity value.',
        avoid: 'Skipping the EV-to-equity bridge.',
      },
      status: 'approved',
    },
    {
      id: 'VA-07',
      text: 'Is an acquisition accretive or dilutive? How do you tell quickly?',
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Merger maths.',
        hit: "Compare the acquirer's P/E with the target's, or the cost of each funding source.",
        avoid: 'Saying accretion means a good deal.',
      },
      status: 'approved',
    },
    {
      id: 'DP-04',
      text: "Locked box vs completion accounts: what's the difference?",
      type: 'technical',
      level: 'mid',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'SPA price mechanisms.',
        hit: 'Fixed price with leakage protection vs post-completion true-up; who bears risk and when each suits.',
        avoid: 'Mixing up leakage and true-up.',
      },
      status: 'approved',
    },
    {
      id: 'SM-04',
      text: 'Why do so many acquisitions fail to create value?',
      type: 'curveball',
      level: 'all',
      scope: { industryId: 'm-and-a', roleFamilyId: 'm-and-a' },
      tips: {
        asking: 'Critical thinking.',
        hit: 'Overpaying, optimistic synergies, culture clash, poor integration, distraction from the core.',
        avoid: 'Giving only one reason.',
      },
      status: 'approved',
    },
  ],
};
