/** 10 seed questions × 3 answers. Expected Content: strong → Strong, partial → Good, off-topic → Needs work. */
export type GoldenAnswer = { questionId: string; kind: 'strong' | 'partial' | 'off-topic'; text: string };

export const goldenAnswers: GoldenAnswer[] = [
  { questionId: 'FE-01', kind: 'strong', text: 'JavaScript runs on a single call stack. When the stack is empty the event loop takes work from the queues. Callbacks like setTimeout go to the task queue, while promise callbacks go to the microtask queue, and the microtask queue drains first after each task. For example, if I log one, schedule a setTimeout that logs two, and resolve a promise that logs three, the order is one, three, two.' },
  { questionId: 'FE-01', kind: 'partial', text: 'The event loop is how JavaScript handles async code. There is a call stack where functions run, and when something async finishes its callback waits in a queue until the stack is clear, then the event loop pushes it onto the stack.' },
  { questionId: 'FE-01', kind: 'off-topic', text: 'I would start by gathering requirements from the product team, then set up a design system with reusable buttons and forms, and make sure the colours and spacing are consistent across every page of the app.' },

  { questionId: 'FE-03', kind: 'strong', text: 'First the browser resolves the domain with DNS to get an IP address. It opens a TCP connection and does the TLS handshake for HTTPS, then sends an HTTP request. When the HTML arrives the browser parses it into the DOM and parses the CSS into the CSSOM. Together they form the render tree, then the browser does layout to work out positions and paint to draw pixels. Finally JavaScript loads and hydration makes the page interactive.' },
  { questionId: 'FE-03', kind: 'partial', text: 'The browser looks up the domain using DNS, connects to the server and sends an HTTP request. The server returns HTML, and the browser parses the HTML and shows the page to the user once it has downloaded the scripts.' },
  { questionId: 'FE-03', kind: 'off-topic', text: 'My favourite project was a mobile app for booking gym classes. I worked with two other developers, we used weekly sprints, and I learned a lot about working with designers and getting feedback from real users.' },

  { questionId: 'FE-06', kind: 'strong', text: 'I start with semantic HTML, like a real button to open it, and only add ARIA roles where native elements fall short, such as role dialog with aria modal. For a modal I trap focus inside while it is open and return focus to the trigger when it closes. I make sure there is full keyboard support, Escape to close and arrow keys in a dropdown, and I test it with a screen reader like VoiceOver.' },
  { questionId: 'FE-06', kind: 'partial', text: 'I would add ARIA attributes like aria label and aria expanded so screen readers know what it is, and make sure the dropdown can be opened with the keyboard as well as the mouse.' },
  { questionId: 'FE-06', kind: 'off-topic', text: 'For performance I would lazy load images, split the bundle by route, and cache API responses so the page loads faster on slow networks.' },

  { questionId: 'RE-03', kind: 'strong', text: 'useEffect synchronises a component with something outside React. The dependency array decides when it re-runs, so every value it reads should be listed. It can return a cleanup function, for example to unsubscribe or abort a fetch. A common mistake is using an effect when you might not need an effect at all: you can derive state during render, or put the logic in an event handler instead.' },
  { questionId: 'RE-03', kind: 'partial', text: 'useEffect runs after the component renders. You pass a dependency array so it only runs when those values change, and a common mistake is leaving values out of the array, which causes stale data in the component.' },
  { questionId: 'RE-03', kind: 'off-topic', text: 'Redux is a state management library with a single store, actions and reducers. I like Redux Toolkit because it removes a lot of the boilerplate and makes the store easier to set up.' },

  { questionId: 'NX-04', kind: 'strong', text: 'Server Actions are functions that run on the server and can be called directly from forms or client components. The big risk is that they are public endpoints, so anyone can call them with any payload. I validate input with a schema and authorise every call by checking the session and permissions inside the action. After a mutation I revalidate the affected paths or tags so the UI shows fresh data.' },
  { questionId: 'NX-04', kind: 'partial', text: 'Server Actions let you run server code from a form without writing an API route. They are convenient for mutations, but you have to be careful about security because they run on the server and can be called.' },
  { questionId: 'NX-04', kind: 'off-topic', text: 'I usually deploy my projects to Vercel and connect the GitHub repository so every pull request gets a preview deployment that the team can review before merging.' },

  { questionId: 'BE-02', kind: 'strong', text: 'An index is a separate data structure, usually a B-tree, that lets the database look up rows quickly instead of doing a full table scan. With a composite index the column order matters, because it can only be used from the leftmost column. Indexes can hurt because every insert and update must also update the index, so writes get slower, and they take extra storage.' },
  { questionId: 'BE-02', kind: 'partial', text: 'An index makes queries faster, a bit like the index at the back of a book, so the database does not have to scan every row to find what you want, and it uses a tree structure.' },
  { questionId: 'BE-02', kind: 'off-topic', text: 'I prefer working in small teams where everyone reviews each other\'s code and we have a clear definition of done for every ticket before it moves to testing.' },

  { questionId: 'BE-04', kind: 'strong', text: 'I would require a client-supplied idempotency key on every payment request. The server stores the key together with the result of the first attempt. If the same key arrives again, it returns the stored result instead of charging twice. To handle concurrent duplicates, I insert the key with a unique constraint before processing, so a second request arriving at the same time is rejected or waits.' },
  { questionId: 'BE-04', kind: 'partial', text: 'I would give each request an idempotency key so that if the client retries we can check whether the payment already happened and avoid charging the customer twice.' },
  { questionId: 'BE-04', kind: 'off-topic', text: 'I would choose PostgreSQL for most projects because it is reliable, supports JSON columns and has a great ecosystem of tools and hosting options.' },

  { questionId: 'ND-01', kind: 'strong', text: 'Node runs all your JavaScript on one thread, so if a request does heavy CPU work, like hashing or parsing a huge file, it stalls every other request waiting on that thread. To avoid it I keep I/O asynchronous, move CPU-heavy work to worker threads, or push it onto a job queue that a separate worker process handles.' },
  { questionId: 'ND-01', kind: 'partial', text: 'Blocking the event loop is bad because Node runs JavaScript on one thread, so the server becomes slow and unresponsive for other users while it is busy.' },
  { questionId: 'ND-01', kind: 'off-topic', text: 'TypeScript adds static types to JavaScript, which catches bugs earlier and makes refactoring large codebases much safer for the whole team.' },

  { questionId: 'FS-02', kind: 'strong', text: 'I would compare session cookies with tokens. For a web app I prefer an HttpOnly session cookie with SameSite set, so JavaScript cannot read it, and I add CSRF protection for state-changing requests. If the API needs tokens, I use short-lived access tokens with a token refresh flow. Either way the API authorises on the server every time, checking permissions on each request rather than trusting the client.' },
  { questionId: 'FS-02', kind: 'partial', text: 'I would use tokens. The user logs in, the server returns a token, the frontend sends it on every request, and when it expires we do a token refresh to get a new one.' },
  { questionId: 'FS-02', kind: 'off-topic', text: 'For styling I like Tailwind because utility classes keep the CSS close to the markup and the design stays consistent across components.' },

  { questionId: 'VA-02', kind: 'strong', text: 'You project the company\'s unlevered free cash flow, the unlevered FCF, for around five years. Then you calculate a terminal value using either a perpetuity growth rate or an exit multiple. You discount the cash flows and terminal value back at the WACC, and sum them to get enterprise value, the EV. Finally you bridge from enterprise value to equity value by subtracting net debt.' },
  { questionId: 'VA-02', kind: 'partial', text: 'A DCF values a company based on its future cash flows. You forecast the free cash flows, add a terminal value, and discount them back to today to get the value of the business.' },
  { questionId: 'VA-02', kind: 'off-topic', text: 'I am interested in this bank because of its culture and its strong presence in the technology sector, and I enjoyed meeting the team at the careers fair last month.' },
];
